### ISSUE TITLE
Persist and restore VM state on disk.

### ISSUE THREAD

**Issue by krl** [dusk-network/hatchery#1]
Persistance of VM memory on disk.

Step 1: 

Our model requires us to be able to persist the state of the vm to disk, and restore it at a later point.

Wasmer is already using memory mapping under the hood, but we will need more control over the files used.

Step 2: 

We need to be able to store a snapshot for a later rollback. Since our model includes knowing which parts of memory have actually been mutably accessed, we should be able to store deltas for only the things that have changed between snapshots.

**Comment by ureeves** [comment]
Closed as obsolete
