### ISSUE TITLE
Port `self-snapshot` test from `rusk-vm`

### ISSUE THREAD

**Issue by ureeves** [dusk-network/hatchery#24]
**Describe what you want implemented** 
The self-snapshot test should be ported from [`rusk-vm`](https://github.com/dusk-network/rusk-vm).

**Describe "Why" this is needed**
Tests included in `rusk-vm` should be ported to this repo for assurance on feature parity. In this test, certain invariants are asserted to be preserved that should also be preserved here.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by krl** [comment]
fixed by #29

**Comment by krl** [comment]
#45 is a regression on this, i propose we reopen this rather than waiting to merge since there's no completely clear view on why this actually worked in the first place. Also the original test uses raw transactions, which we should replicate now that #30 is landed.

**Comment by ureeves** [comment]
Closing as obsolete after discussion with @krl
