### ISSUE TITLE
Upgrade to `wasmer` latest version

### ISSUE THREAD

**Issue by ureeves** [dusk-network/hatchery#44]
**Describe what you want implemented** 
Upgrade the `wasmer` dependency to the newest version.

**Describe "Why" this is needed**
Since `wasmer` introduces quite some changes we should get on it early before our VM is too coupled to the current version.

**Describe alternatives you've considered**
Not upgrading and staying on this version would be an option, but might lead to problems in the future since we would like to use some of the upcoming features.

**Additional context**
N/A

**Comment by miloszm** [comment]
Upgrade becomes critical with change 3119 regarding linear memory trait has been pushed to Wasmer master. Using this latest version lets us eliminate Wasmer's fork and progress with additional mmap-related functionality, hence migration is now on a critical path.

**Comment by miloszm** [comment]
We got information that 3.0.0-beta with linear memory trait will be released soon.

**Comment by ureeves** [comment]
Taked about it with @miloszm. Closing as done
