### ISSUE TITLE
Session Commits Persistence

### ISSUE THREAD

**Issue by miloszm** [dusk-network/hatchery#89]
#### Summary
> 💡 After system is restarted, we need to be able to find and restore session's commits that have been performed in the past.

#### Possible solution design or implementation
> 💡 TBD

#### Additional context
> 💡 The following minimal test T1 expressed as pseudocode should work:

start VM
deploy module M1 with initial state S1
start session S
assert state of M1 is S1
set state of M1 to S2
commit session S, obtain commit id CID1
drop session S
start session S
restore session to CID1
assert state of M1 is S2

Note that this issue is about session level persistence:

Session level persistence - session's commit method produces a session_commit_id which can be used at later time as argument to session's restore method. Note, that here we can distinguish: a) persistence of particular commits, under the assumption that the user stores commit ids, as well as b) persistence of commit ids themselves, under the assumption that the user does not store them.

**Comment by ureeves** [comment]
Closed by #98
