### ISSUE TITLE
Implement automated WASM memory growth mechanism

### ISSUE THREAD

**Issue by miloszm** [dusk-network/hatchery#9]
**Describe what you want implemented** 
Memory allocation mechanism should detect when heap is about to be exhausted and grow memory automatically.

**Describe "Why" this is needed**
This is needed because it is hard and inconvenient for the user to manually predict the size of memory needed.

**Describe alternatives you've considered**
An alternative is to manually grow memory, this is our default approach but we want to improve on that.

**Additional context**
World's deploy method has now `grow_mem_by` parameter for memory growth, we want to automate that.

**Comment by ureeves** [comment]
Obsolete
